### ISSUE TITLE
Target vs Compiler confusion

### ISSUE THREAD

**Issue by TwoClocks** [mahkoh/repr-c#3]
I'm trying to translate `repr-c` targets to `zig` targets, which have a more structured format (At least internally). So I'm trying to de-couple compiler from target in `repr-c`.

All the things that affect layout besides compiler in `common.rs` look like target differences, not compiler differences. Except `unnamed_field_affects_record_alignment()`.  All the `arch64` platforms return `ture` except `AppleMacosx` and `PcWindowsMsvc`. The windows one makes sense, as it's a different compiler. But the OSX is the same compiler (Clang) as most of the rest of the others. 

This may be my ignorance, but why would OS affect layout if the compiler(s) and hardware are the same? I also assume that OSX has the same ABI as BSD, which also returns 'true'

**Comment by mahkoh** [comment]
>I also assume that OSX has the same ABI as BSD

It does not https://reviews.llvm.org/D89490

https://github.com/llvm/llvm-project/blob/b46ad1b5be694feefabd4c6cd112cbbd04a7b3a7/clang/lib/Basic/Targets/AArch64.cpp#L114-L119

https://github.com/llvm/llvm-project/blob/b46ad1b5be694feefabd4c6cd112cbbd04a7b3a7/clang/lib/Basic/Targets/AArch64.cpp#L1018

**Comment by TwoClocks** [comment]
How odd. I wonder why Apple decided to do that? Seems like such a minor thing to change.

Thanks for the links. Great resource.
